Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Description: >-
                 Add the frozen_string_literal comment to the top of files
                 to help transition from Ruby 2.3.0 to Ruby 3.0.
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/LineLength:
  Max: 110

MethodLength:
  Max: 20

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'tmp/**/*'
    - 'config/**/*'
    - 'bin/**'
    - 'db/**/*' 
  TargetRubyVersion: 2.3
