lenguage: ruby
rvm:
- 2.3.0
script: bundle exec rspec
addons:
  code_climate:
    repo_token:
      secure: aLeFdBUDKf7cf+dl8+ijBIY7VmVcNUXAWWpd2VYFKy4yAZ5yI+fWPngJrdi9GjvubSkikHnx/x9eDeCI3SHANXgOtAEI1Bx52tPsq4sHb71zRSQ8NBbaDVw+KqlL5qVMSohlwGwoWGqoz/flknfz7EXjCBg3hwxIX+FpxIrjGGzrrzZjQr4M9x9So2CvgOisut0FL8q5aifRuJ25dVCr77vNB5hm2XQn6vusOYz1OYt0Hh7e1vSStM6+3pP3UoOSCT6qN9Kw3mdoRL1PoabkvW8XiGBXM/pZulWl7pmgyzcPdMym9OFX9ShEPUpn+oSwoIB068DW7udJ7pA3nfH/jTfHFRYem2KCgiSFErPNflfV70io0wBOLaYW6QIE4FJPIBLnPPzTzNBcQd8baPS9gMzMh/5d94VYtMgWLjX+jHV/b8DX0FSg9NWEhmMMtKGHGmOAQ+1AQN7a+14k5CPvUEYcRiMocQLr6Vh2vMJTUgjhQIwsNv6WczTFDW+0Ykdp+CYO4vgIEkwdy4X2UaDP9SQbFZVRAn0nVKtglc5xgThvcxj+x83zFsGqT6gLgPSfukT+j9InOQWF/JP/QfszJl1zNlyeVFLBNmhZoq7WK40fqBlL4IlE3b5DY1d9dAPpiEZs1DmLoqGCBEkcNXpYkfPkN5zq64pFS5Ia5fkj7Vo=
